apiVersion: v1
kind: Service
metadata:
  name: source-code-analyzer-svc
  namespace: source-code-analyzer
spec:
  selector:
    app: source-code-analyzer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
